### ISSUE TITLE
Can't run in VSCode in macOS

### ISSUE THREAD

**Issue by mhmdio** [paulvarache/vscode-taskfile#11]
- VScode on macOS
- Taskfile installed via Brew `brew install go-task/tap/go-task`
- use case: _Manage Terraform operations_

```bash
❯ which task                
/usr/local/bin/task

❯ task --version            
Task version: 3.2.2

❯ code -v               
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```

**Got the following error:**
<img width="953" alt="Screen Shot 2021-01-26 at 4 24 10 PM" src="https://user-images.githubusercontent.com/11231023/105857542-10e3fa80-5ff3-11eb-8752-5a05639e1808.png">

**Install Task as shown dose nothing:**
<img width="600" alt="Screen Shot 2021-01-26 at 4 37 23 PM" src="https://user-images.githubusercontent.com/11231023/105859082-c794aa80-5ff4-11eb-90bd-5fa04d0ea34c.png">

**Comment by xmlking** [comment]
same issue for me

**Comment by sheldonhull** [comment]
bump. Same here.

**Comment by paulvarache** [comment]
Hi,

I am fairly confident I have found the source of the issue and have a branch ready with a fix.

Unfortunately, I am unable to test anything on macOS (legally), so I will need some of you to test a preview release to confirm it does work.

This fix will ensure the install task binary command runs on macOS and Linux properly, it does not make the extension detect already installed task binaries.

The .vsix file for the extension can be found here: https://github.com/paulvarache/vscode-taskfile/releases/tag/0.0.6-alpha.1

**Comment by mhmdio** [comment]
I will test it' despite living in a war zone nowadays

**Comment by mhmdio** [comment]
it worked, but depends on the `Taskfile`, for example, this `Taskfile` is not working as expected:

**`Taskfile`**:
```yml
# https://taskfile.dev

version: "3"
output: prefixed
silent: true

env:

vars:
  ENV: dev
  REGION: eu-central-1

tasks:
  default:
    cmds:
      - echo ">> Environment {{.ENV}} Region {{.REGION}}"

  tfdoc:
    desc: terraform-docs - A utility to generate documentation from Terraform modules in various output formats
    dir: "env/{{.ENV }}/{{.REGION}}"
    cmds:
      - terraform-docs markdown . --config ../../../.terraform-docs.yml --output-file README.md

  kubeconfig:
    desc: kubeconfig - Allow kubectl access to EKS cluster
    dir: "env/{{.ENV }}/{{.REGION}}"
    cmds:
      - mkdir -p $HOME/.kube
      - terraform output -raw kubeconfig > $HOME/.kube/config
```

**`Taskfile` log output:**

```log
[jsonrpc] 2021/05/15 18:39:19 Found Handler for method initialize
[jsonrpc] 2021/05/15 18:39:19 Sending response: {"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1},"completionProvider":{"resolveProvider":true}}},"error":null,"id":0}
[jsonrpc] 2021/05/15 18:39:19 Found Handler for method initialized
[jsonrpc] 2021/05/15 18:39:19 Sending response: {"result":null,"error":null,"id":0}
[jsonrpc] 2021/05/15 18:39:21 Found Handler for method extension/getTasks
[jsonrpc] 2021/05/15 18:39:21 Sending response: {"result":[],"error":null,"id":1}
[jsonrpc] 2021/05/15 18:39:21 Found Handler for method extension/getTasks
[jsonrpc] 2021/05/15 18:39:21 Sending response: {"result":[],"error":null,"id":2}
[jsonrpc] 2021/05/15 18:39:33 Found Handler for method extension/getTasks
[jsonrpc] 2021/05/15 18:39:33 Sending response: {"result":[],"error":null,"id":3}
[jsonrpc] 2021/05/15 18:39:33 Found Handler for method extension/getTasks
[jsonrpc] 2021/05/15 18:39:33 Sending response: {"result":[],"error":null,"id":4}
```

Another `Taskfile` is working as expected:
```yml
version: '3'

includes:
  dev:
    taskfile: ./xyz-terraform-dev/Taskfile.yml
    dir: ./xyz-terraform-dev
  prod:
    taskfile: ./xyz-terraform-prod/Taskfile.yml
    dir: ./xyz-terraform-prod
  shared:
    taskfile: ./xyz-terraform-shared/Taskfile.yml
    dir: ./xyz-terraform-shared
  master:
    taskfile: ./xyz-terraform-master/Taskfile.yml
    dir: ./xyz-terraform-master


tasks:
  default:
    cmds:
      - echo ">> Environment {{.ENV}} >> Stack {{.STACK}}"
  login:
    desc: Login using aws-vault.
    cmds:
      - aws-vault remove --sessions-only {{.PROJECT}}-{{.ENV}}
      - aws-vault --version
      - aws-vault exec {{.PROJECT}}-{{.ENV}} --duration=2h
    silent: true
```

and General notes:
- when clicking on a task it will not take you to file ( unless to use right-click and edit task - although this one only bring the task to the middle of the file with no cursor)
- install Task binary is working as expected
- other general Taskfile features work as expected ( run - watch - edit )
- Install LSP do nothing ( not sure about this - need someone else to test it also)
