### ISSUE TITLE
not showing all the tasks 

### ISSUE THREAD

**Issue by xmlking** [paulvarache/vscode-taskfile#12]
I have 
```yml
includes:
  config:     ./config
  proto:      task/proto.yml
  go:         task/go.yml
  mod:        task/mod.yml
  install:    task/install.{{OS}}.yml
  build:      task/build.{{OS}}.yml
 ```

full source: https://github.com/xmlking/grpc-starter-kit

but vs code only showing few

![image](https://user-images.githubusercontent.com/627951/105889162-b8950480-5fc2-11eb-81f6-e3646da9d5b0.png)
