### ISSUE TITLE
Show only Taks until line comment

### ISSUE THREAD

**Issue by Obladio** [paulvarache/vscode-taskfile#24]
Nice Tool!

looks like it just shows all tasks until it a line comment is inserted in the taskfile. 
```yaml
...
tasks:
  task1:
    cmds:
      - echo "foo"

  task2:
    cmds:
      - echo "bar"
```
--> Show task1 and task2 in Taskfile outline.
```yaml
...
tasks:
  task1:
    cmds:
      - echo "foo"
 #some important comment
  task2:
    cmds:
      - echo "bar"
```
--> Shows task1 in Taskfile outline.

Seen in VS Code Extension: 
More Info
Released on
1/19/2020, 19:58:37
Last updated
1/26/2021, 11:26:23
Identifier
paulvarache.vscode-taskfile
