### ISSUE TITLE
Incorrect schema error on version: "3"

### ISSUE THREAD

**Issue by lukepighetti** [paulvarache/vscode-taskfile#28]
```yaml
version: "3"

vars:
  GREETING: Hello, World!

tasks:
  my-task:
    cmds:
      - foo
    interactive: true
```

<img width="901" alt="Screen Shot 2022-03-25 at 10 27 57 AM" src="https://user-images.githubusercontent.com/666539/160140146-3c9eeab5-5eaa-49bf-a283-9cc6f0819dab.png">
