### ISSUE TITLE
Syntax error with `deps` dependencies

### ISSUE THREAD

**Issue by klauern** [paulvarache/vscode-taskfile#3]
Hello!  I was super excited to find this extension and installed it, but it appears there's an error with one of my dependencies:

```yaml
  bump:
    desc: Bump the version
    deps:
      - task: build:generated-dir
```
![image](https://user-images.githubusercontent.com/4735/81845079-a860f600-9515-11ea-91ee-cf300beb40d5.png)

Note that this is proper syntax, and is outlined in the section on task dependencies: https://taskfile.dev/#/usage?id=task-dependencies

```yaml
version: '2'

tasks:
  default:
    deps:
      - task: echo_sth
        vars: {TEXT: "before 1"}
      - task: echo_sth
        vars: {TEXT: "before 2"}
    cmds:
      - echo "after"

  echo_sth:
    cmds:
      - echo {{.TEXT}}
```
